# Generated by Django 4.2.6 on 2023-10-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('user', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.ManyToManyField(to='auctions.bid'),
        ),
    ]
