# Generated by Django 4.2.6 on 2023-10-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_listing_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bids',
            field=models.ManyToManyField(to='auctions.bid', verbose_name='agbjhg'),
        ),
    ]
