# Generated by Django 4.2.6 on 2023-10-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_rename_value_bid_amount_alter_listing_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bids',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.bid'),
        ),
    ]
