# Generated by Django 4.0.6 on 2023-10-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
